<?php
// 1. START OUTPUT BUFFERING IMMEDIATELY
// This captures anything printed (errors, whitespace) so we can delete it before sending JSON.
ob_start();

require_once 'config.php';
setHeaders();

// Error logging setup (Internal logs only, do not display to user)
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);
ini_set('error_log', 'php_errors.log'); 

// 2. CLEAN BUFFER
// Delete any whitespace/warnings generated by the includes above
ob_clean();

try {
    $conn = connectDB();
    $input_data = file_get_contents("php://input");
    
    // Log raw input for debugging (optional)
    // error_log("updateSetting.php - Received: " . $input_data);
    
    $data = json_decode($input_data, true);

    if (!isset($data['key_name']) || !isset($data['key_value'])) {
        throw new Exception("Key name or value missing.");
    }

    $key_name = $data['key_name'];
    $key_value = $data['key_value'];

    // Prepare SQL
    $sql = "UPDATE settings SET key_value = ? WHERE key_name = ?";
    $stmt = $conn->prepare($sql);

    if (!$stmt) {
        throw new Exception("SQL Prepare failed: " . $conn->error);
    }

    // --- BINDING LOGIC (Preserved from your code) ---
    if (in_array($key_name, ['price', 'offer_price', 'total_revenue', 'total_sales'])) {
        $stmt->bind_param("ds", $key_value, $key_name); // Double, String
    } else {
        $stmt->bind_param("ss", $key_value, $key_name); // String, String
    }

    // Execute
    if ($stmt->execute()) {
        if ($stmt->affected_rows > 0) {
            $response = ["success" => true, "message" => "Setting updated successfully."];
        } else {
            // Check if it was 0 because it failed or just wasn't changed
            // If the query worked but data was same, it's still a success
            $response = ["success" => true, "message" => "Value saved (No changes detected)."];
        }
    } else {
        throw new Exception("Execution failed: " . $stmt->error);
    }

    $stmt->close();
    $conn->close();

    echo json_encode($response);

} catch (Exception $e) {
    http_response_code(500);
    error_log("updateSetting.php Error: " . $e->getMessage());
    echo json_encode(["success" => false, "message" => $e->getMessage()]);
}

// 3. FLUSH BUFFER
ob_end_flush();
?>